# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 229fb3f02ebb249506cf599506c2ee71573d48e45405ceed536a571a9e5c221ac80584d491be80a1e5cd2fcdde2cb29997bbf67f63d2a234e9b693b44c6d6669

test:
  secret_key_base: 0c2d1f595587345f5f51363523f964912b33af7d7cf1b58774928b7a206da23928e4ab332bdf9c45ca41fba68d7d7e1c0469d503ed1dc66d1bc940adc7b66e38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
